name: Build Android Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pystray requests pyinstaller packaging
    
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --icon="icon.ico" --uac-admin --version-file="version.txt" --name="Android Emulator" android_setup.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Android-Emulator
        path: dist/Android Emulator.exe
    
    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/Android Emulator.exe
        asset_name: Android-Emulator.exe
        asset_content_type: application/octet-stream
