name: Build Android Emulator

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow pystray requests pyinstaller packaging
    
    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole --icon="icon.ico" --uac-admin --version-file="version.txt" --name="Android Emulator" android_setup.py
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-Emulator
        path: dist/Android Emulator.exe
        retention-days: 90
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: ./dist/Android Emulator.exe
        generate_release_notes: true
